name: sudoku_flutter
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# 앱 버전 (빌드 시 +1 증가 필요)
version: 1.1.0+20

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  
  url_launcher: ^6.3.0
  cupertino_icons: ^1.0.8
  audioplayers: ^6.5.1
  flame: ^1.32.0
  flame_audio: ^2.10.1
  shared_preferences: ^2.2.3
  provider: ^6.1.5+1
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  google_mobile_ads: ^6.0.0

  firebase_core: ^4.2.0
  cloud_firestore: ^6.0.3
  firebase_storage: ^13.0.3
  firebase_auth: ^6.1.1
  google_sign_in: ^6.2.1
  webview_flutter_android: ^4.10.5
  firebase_remote_config: ^6.1.0
  package_info_plus: ^9.0.0

  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.0

flutter:
  generate: true

  # 머터리얼 아이콘 사용
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/sounds/
    - assets/images/
    - assets/stages/

flutter_gen:
  l10n:
    arb-dir: lib/l10n
    template-arb-file: app_en.arb
    output-localization-file: app_localizations.dart
    output-class: AppLocalizations
    preferred-supported-locales: [en, ko, ja, zh]

flutter_launcher_icons:
  # 앱 아이콘 설정
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/icon.png"
